# Generated by Django 3.2.3 on 2021-09-25 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField()),
                ('goal', models.PositiveIntegerField()),
                ('percent', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('cost', models.PositiveIntegerField()),
                ('Money', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='Money.money')),
            ],
        ),
    ]
