# Generated by Django 3.2.3 on 2021-09-26 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Money', '0003_auto_20210926_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='money',
            name='percent',
        ),
    ]
