# Generated by Django 3.2.3 on 2021-09-25 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cost', models.PositiveIntegerField()),
                ('goal', models.PositiveIntegerField()),
                ('now', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('cost', models.PositiveIntegerField()),
                ('Challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Challenge.challenge')),
            ],
        ),
    ]
