# Generated by Django 3.2.3 on 2021-09-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Challenge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='Challenge',
            new_name='which_challenge',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='now',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
