<<<<<<< HEAD
# Generated by Django 3.2 on 2021-09-25 02:23
=======
# Generated by Django 3.2.3 on 2021-09-25 02:04
>>>>>>> 831d734403ca555cc7e36df330829f0b5935675a

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Challenge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('cost', models.PositiveIntegerField()),
                ('Challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Challenge.challenge')),
            ],
        ),
    ]
