# Generated by Django 3.2.3 on 2021-09-25 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Challenge', '0003_rename_which_challenge_history_challenge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='Challenge',
            new_name='challenge',
        ),
    ]
