# Generated by Django 3.2.3 on 2021-09-25 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('goal', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('hobby', models.CharField(choices=[('미술', '미술'), ('레저', '레저'), ('음악', '음악'), ('공예', '공예'), ('스포츠', '스포츠'), ('재테크', '재테크'), ('여행', '여행'), ('사업', '사업')], default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('goal', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'db_table': 'Plan',
            },
        ),
    ]
