# Generated by Django 3.2.3 on 2021-09-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendplan',
            name='goal',
            field=models.CharField(max_length=200),
        ),
    ]
